int latchPin = 12; // Latch pin of 74HC595 is connected to Digital pin 5
int clockPin = 13; // Clock pin of 74HC595 is connected to Digital pin 6
int dataPin = 14;  // Data pin of 74HC595 is connected to Digital pin 4
int oePin = 5;     // oePin - not using this

uint16_t Data;

void setup()
{
      // Set all the pins of 74HC595 as OUTPUT
      pinMode(latchPin, OUTPUT);
      pinMode(dataPin, OUTPUT);
      pinMode(clockPin, OUTPUT);
      pinMode(oePin, OUTPUT);
}

void loop()
{

      Data = 0b0000000000000001;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b0000000000000011;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b0000000000000111;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b0000000000001111;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b0000000000011111;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b0000000000111111;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b0000000001111111;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b0000000011111111;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b0000000111111111;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b0000001111111111;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b0000011111111111;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b0000111111111111;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b0001111111111111;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b0011111111111111;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b0111111111111111;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b1111111111111111;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b1111111111111110;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b1111111111111100;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b1111111111111000;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b1111111111110000;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b1111111111100000;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b1111111111000000;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b1111111110000000;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b1111111100000000;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b1111111000000000;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b1111110000000000;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b1111100000000000;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b1111000000000000;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b1110000000000000;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b1100000000000000;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b1000000000000000;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
      Data = 0b0000000000000000;
      digitalWrite(latchPin, LOW);
      shiftOut(dataPin, clockPin, MSBFIRST, (Data >> 8));
      shiftOut(dataPin, clockPin, MSBFIRST, Data);
      digitalWrite(latchPin, HIGH);
      delay(100);
}